# https://cibuildwheel.pypa.io/en/stable/setup/#github-actions
name: CI Build Wheel

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # want to see all failures
      fail-fast: false
      matrix:
        # macos-14, macos-13: compiles okay, tests segfault at import time
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: runner.os=='Windows'
        with:
          arch: x64
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
