# https://cibuildwheel.pypa.io/en/stable/setup/#github-actions
name: CI Build Wheel

on: [push, pull_request]

env:
  # (a) skip all 32-bit builds (source issue: datastream.h assumes size_t != unsigned long, which break on 32bit)
  # (b) skipy pypy builds: embedding interpreter not supported (pythonfield.C)
  # (c) skip all musllinux builds (compiles but segfaults at import time)
  CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *musllinux*"
  # https://cibuildwheel.pypa.io/en/stable/cpp_standards/#macos-and-deployment-target-versions
  MACOSX_DEPLOYMENT_TARGET: 10.14
  # on Linux, also build pyodide (wasm), but not i686
  CIBW_BUILD_LINUX: "x86_64 wasm"

  # Use delvewheel on windows: https://github.com/pypa/cibuildwheel/discussions/1798
  #CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
  #CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # want to see all failures
      fail-fast: false
      matrix:
        # macos-14: compiles okay, tests segfault at import time
        # macos-13: same
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
