# https://cibuildwheel.pypa.io/en/stable/setup/#github-actions
name: CI Build Wheel

on: [push, pull_request]

env:
  # skipy pypy builds: embedding interpreter not supported (pythonfield.C)
  CIBW_SKIP: pp*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # want to see all failures
      fail-fast: false
      matrix:
        # macos-14: compiles okay, tests segfault at import time
        # macos-13: same
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
